name: Build And Deploy Test
on:
  workflow_dispatch: 
      inputs:
        branch:
            description: 'Define branch name'
            required: true
            default: 'master'
jobs:
  build-components:
    strategy:
      matrix:
        component: [Api, Interface]  
    uses: ./.github/workflows/z_BuildAndDeployComponent.yml
    with:
        type: ${{ matrix.component }}  
        branch: ${{ github.event.inputs.branch }}
    secrets: inherit

