name: Build And Deploy Vario Business Component
on:
    workflow_call:
        inputs:
            type:
                description: 'Define Application Type'
                required: true
                type: string
            branch:
                description: 'Define Branch to check-out'
                required: true
                type: string
                default: 'master'

#concurrency: 
#  group: ${{ github.workflow }}-${{ inputs.type }}-${{ github.ref }}
#  cancel-in-progress: true
env:
    CONFIGURATION: Release
    DOTNET_CORE_VERSION: 8.0.x
  
jobs:
    initialize:
        runs-on: ubuntu-latest
        outputs:
            WORKING_DIRECTORY: ${{ steps.InitVariables.outputs.WORKING_DIRECTORY }}
            AZURE_WEBAPP_PACKAGE_PATH: ${{ steps.InitVariables.outputs.AZURE_WEBAPP_PACKAGE_PATH }}
            ARTIFACT_NAME: ${{ steps.InitVariables.outputs.ARTIFACT_NAME }}
        steps:
        - name: InitVariables
          shell: bash
          run: |
            if [ "${{ inputs.type }}" = "Api" ]; then
                    export  WORKING_DIRECTORY="${{ github.workspace }}/WorkflowTestRepository"
                elif [ "${{ inputs.type }}" = "Interface" ]; then
                    export  WORKING_DIRECTORY="${{ github.workspace }}/WorkflowTestRepository.Interface"
                fi

                if [ "${{ inputs.type }}" = "Api" ]; then
                    export  AZURE_WEBAPP_PACKAGE_PATH="${{ github.workspace }}/WorkflowTestRepository/publish"
                elif [ "${{ inputs.type }}" = "Interface" ]; then
                    export  AZURE_WEBAPP_PACKAGE_PATH="${{ github.workspace }}/WorkflowTestRepository.Interface/publish"
                fi

                if [ "${{ inputs.type }}" = "Api" ]; then
                    export  ARTIFACT_NAME="WorkflowTestRepositoryAPI"
                elif [ "${{ inputs.type }}" = "Interface" ]; then
                    export ARTIFACT_NAME="WorkflowTestRepositoryInterface"
                fi

                echo "WORKING_DIRECTORY=$WORKING_DIRECTORY" >> "$GITHUB_OUTPUT"
                echo "AZURE_WEBAPP_PACKAGE_PATH=$AZURE_WEBAPP_PACKAGE_PATH" >> "$GITHUB_OUTPUT"
                echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

                echo "$WORKING_DIRECTORY - $AZURE_WEBAPP_PACKAGE_PATH - $ARTIFACT_NAME"
    build:
        runs-on: ubuntu-latest
        needs: initialize
        steps:
        - uses: actions/checkout@v3
          with: 
                ref: ${{ inputs.branch}}
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        - name: Show Secret 
          run: |
            echo "Printing the secret value '${{ secrets.AVerySenstiveSecret }}' "    
            echo "Secret ${{ secrets.AVerySenstiveSecret }}"    
            echo "Working Dir ${{ needs.initialize.outputs.WORKING_DIRECTORY }}"
        - name: Restore
          run: dotnet restore "${{ needs.initialize.outputs.WORKING_DIRECTORY }}"
        - name: Build
          run: dotnet build "${{ needs.initialize.outputs.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
        - name: Publish
          run: dotnet publish "${{ needs.initialize.outputs.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ needs.initialize.outputs.AZURE_WEBAPP_PACKAGE_PATH }}" --no-self-contained
        - name: Publish Artifacts
          uses: actions/upload-artifact@v1.0.0
          with:
            name: ${{ needs.initialize.outputs.ARTIFACT_NAME }}
            path: ${{ needs.initialize.outputs.AZURE_WEBAPP_PACKAGE_PATH }}