name: Build And Deploy Test
on:
  workflow_dispatch: 
      inputs:
        branch:
            description: 'Define branch name'
            required: true
            default: 'master'
jobs:
  build-API:
    uses: ./.github/workflows/z_BuildAndDeployComponent.yml  
    with:
        type: 'Api'  
        branch: ${{ github.event.inputs.branch }}
  build-Interface:
    uses: ./.github/workflows/z_BuildAndDeployComponent.yml  
    with:
        type: 'Interface'  
        branch: ${{ github.event.inputs.branch }}