name: Build And Deploy Test
on:
  workflow_dispatch: 
      inputs:
        branch:
            description: 'Define branch name'
            required: true
            default: 'master'
jobs:
  build-components:
    name: Build ${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [Api, Interface]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and Deploy ${{ matrix.component }}
        uses: ./.github/workflows/z_BuildAndDeployComponent.yml
        with:
          type: ${{ matrix.component }}  
          branch: ${{ github.event.inputs.branch }}
          secrets: inherit

