name: Build And Deploy Test
on:
  workflow_dispatch: 

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/z_BuildAndDeployComponent.yml  
        with:
          type: 'Api'  
          branch: 'master'  
      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/z_BuildAndDeployComponent.yml  
        with:
          type: 'Interface'  
          branch: 'master'  